import streamlit as st
import numpy as np
import cv2

from core.drpe import generate_random_phase_mask, decrypt
from core.utils import ciphertext_magnitude_for_display, to_uint8

def render_decrypt_tab():
    st.header("2. Decrypt a File")
    
    # Initialize the session state so results stay on screen
    if 'decryption_done' not in st.session_state:
        st.session_state['decryption_done'] = False

    # 1. Primary Input
    uploaded_npy = st.file_uploader("Upload Encrypted Data (.npy strictly)", type=['npy'])
    
    if uploaded_npy:
        try:
            loaded_data = np.load(uploaded_npy, allow_pickle=True).item()
            cipher = loaded_data['cipher']
            orig_shape = loaded_data['orig_shape']
        except Exception:
            st.error("Invalid file format. Please upload a valid .npy file generated by this application.")
            return
        
        # 2. Progressive Disclosure: Hide the key management mechanics
        with st.expander("⚙️ Key Management & Security Testing", expanded=True):
            key_mode = st.radio("Select Key Source:", ["Upload Key File", "Enter Manual PIN"], horizontal=True)
            
            valid_k1, valid_k2 = None, None
            
            if key_mode == "Upload Key File":
                uploaded_keys = st.file_uploader("Upload Keys (.npy)", type=['npy'])
                if uploaded_keys:
                    keys_dict = np.load(uploaded_keys, allow_pickle=True).item()
                    valid_k1 = keys_dict['key1']
                    valid_k2 = keys_dict['key2']
                    st.success("[ OK ] Keys loaded into memory.")
            else:
                pin = st.number_input("Enter your numeric PIN", min_value=0, max_value=999999, value=4096)
                valid_k1 = generate_random_phase_mask(cipher.shape, seed=pin)
                valid_k2 = generate_random_phase_mask(cipher.shape, seed=pin + 1)
            
            st.divider()
            attack_mode = st.toggle("🚨 Simulate Wrong Key Attack", help="Intentionally corrupts Key 2 to demonstrate the sensitivity of the DRPE algorithm.")
        
        # 3. Primary Action
        if st.button("./execute_drpe_decryption.sh", type="primary", use_container_width=True):
            if valid_k1 is None or valid_k2 is None:
                st.error("Cannot decrypt: No valid keys provided. Please upload your key file or enter a PIN.")
            else:
                with st.spinner("Reversing 2D Fast Fourier Transform..."):
                    # Apply the attack toggle
                    k1_to_use = valid_k1
                    k2_to_use = generate_random_phase_mask(cipher.shape, seed=9999) if attack_mode else valid_k2
                    
                    # Decrypt and resize
                    recovered = decrypt(cipher, k1_to_use, k2_to_use)
                    final_img = cv2.resize(recovered, (orig_shape[1], orig_shape[0]))
                    final_img = np.clip(final_img, 0, 1)
                    
                    # Save to state
                    st.session_state['dec_cipher'] = cipher
                    st.session_state['dec_final'] = final_img
                    st.session_state['dec_attack'] = attack_mode
                    st.session_state['decryption_done'] = True

        # 4. Output Display
        if st.session_state['decryption_done']:
            c_cipher = st.session_state['dec_cipher']
            c_final = st.session_state['dec_final']
            c_attack = st.session_state['dec_attack']

            st.divider()
            col1, col2 = st.columns(2)
            with col1:
                st.image(to_uint8(ciphertext_magnitude_for_display(c_cipher)), caption="Uploaded Ciphertext", use_container_width=True)
            with col2:
                if c_attack:
                    st.error("ACCESS DENIED: Incorrect phase key applied.")
                    st.image(to_uint8(c_final), caption="Decrypted (White Noise)", use_container_width=True)
                else:
                    st.success("ACCESS GRANTED: Phase keys perfectly canceled.")
                    st.image(to_uint8(c_final), caption="Decrypted (Perfect Recovery)", use_container_width=True)