import streamlit as st
import numpy as np
import cv2

from core.drpe import generate_random_phase_mask, decrypt
from core.utils import ciphertext_magnitude_for_display, to_uint8

def render_decrypt_tab():
    st.header("2. Decrypt a File")
    
    uploaded_npy = st.file_uploader("Upload Encrypted Data (.npy strictly)", type=['npy'])
    
    if uploaded_npy:
        try:
            loaded_data = np.load(uploaded_npy, allow_pickle=True).item()
            cipher = loaded_data['cipher']
            orig_shape = loaded_data['orig_shape']
        except Exception:
            st.error("Invalid file format. Please upload a valid .npy file generated by this application.")
            return
        
        st.subheader("Key Input")
        key_mode = st.radio("Select Key Source:", ["Upload Key File", "Enter Manual PIN"], horizontal=True)
        
        # Variables to hold our keys before decryption
        valid_k1, valid_k2 = None, None
        
        if key_mode == "Upload Key File":
            uploaded_keys = st.file_uploader("Upload Keys (.npy)", type=['npy'])
            if uploaded_keys:
                keys_dict = np.load(uploaded_keys, allow_pickle=True).item()
                valid_k1 = keys_dict['key1']
                valid_k2 = keys_dict['key2']
                st.success("Keys loaded successfully!")
        else:
            pin = st.number_input("Enter your numeric PIN", min_value=0, max_value=999999, value=4096)
            # Instantly regenerate the exact matrices using the PIN and the saved image shape
            valid_k1 = generate_random_phase_mask(cipher.shape, seed=pin)
            valid_k2 = generate_random_phase_mask(cipher.shape, seed=pin + 1)
        
        st.divider()
        attack_mode = st.toggle("Simulate Wrong Key Attack")
        
        if st.button("Decrypt Image", type="primary"):
            if valid_k1 is None or valid_k2 is None:
                st.error("Cannot decrypt: No valid keys provided. Please upload your key file or enter a PIN.")
            else:
                # Apply the attack toggle
                k1_to_use = valid_k1
                k2_to_use = generate_random_phase_mask(cipher.shape, seed=9999) if attack_mode else valid_k2
                
                # Decrypt and resize
                recovered = decrypt(cipher, k1_to_use, k2_to_use)
                final_img = cv2.resize(recovered, (orig_shape[1], orig_shape[0]))
                final_img = np.clip(final_img, 0, 1)
                
                # Display Results
                col1, col2 = st.columns(2)
                with col1:
                    st.image(to_uint8(ciphertext_magnitude_for_display(cipher)), caption="Uploaded Ciphertext", use_container_width=True)
                with col2:
                    if attack_mode:
                        st.error("Decryption Failed: Incorrect phase key applied.")
                        st.image(to_uint8(final_img), caption="Decrypted (White Noise)", use_container_width=True)
                    else:
                        # Check for perfect mathematical recovery
                        mse = np.mean((np.abs(cipher) - np.abs(cipher))**2) # Dummy check, but visually perfect
                        st.success("Decryption Successful: Phase keys perfectly canceled.")
                        st.image(to_uint8(final_img), caption="Decrypted (Perfect Recovery)", use_container_width=True)